server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 50
    lease-expiration-duration-in-seconds: 1000
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

airshop:
  jwt:
    secret: airshop@Love(Auth^33) # 登录校验的密钥
    pubKeyPath: D:\\server\\airshop\\rsa.pub
    priKeyPath: D:\\server\\airshop\\rsa.pri
    expire: 1800 # 过期时间,单位分钟
    cookieName: AIR_TOKEN
    cookieMaxAge: 1800