server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/air_shop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 192.168.13.132
    username: admin
    password: admin
    template:
      retry:
        enabled: true
        max-interval: 210000ms
        initial-interval: 10000ms
        multiplier: 2
    publisher-returns: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 1500
    lease-renewal-interval-in-seconds: 500
